import Head from 'next/head'
import React, { useState, useEffect } from 'react';

// components
import LeftSideBar from '../../components/LeftSideBar';
import Header from '../../components/StandardHeader';
import DifficultyChip from '../../components/DifficultyChip';

// material ui components
import Button from '@mui/material/Button';
import Chip from '@mui/material/Chip';



export default function Home() {
  return (
    <div className="flex flex-row w-full h-full" data-id="home-container">
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <LeftSideBar/>

      <div className="flex flex-col w-full h-full" data-id="main-container">

        <Header/>

        <div className="flex flex-row h-full" data-id="right-container">
          <div className="p-2 flex-1 max-w-sm" data-id="flex-1 grow left-topic-sidebar">
            <h2>
              Information
            </h2>

            <div>
              <h3 className="font-bold">
                What is this?
              </h3>
              <p className="text-slate-600">
                This is a website for practicing your programming skills with a random partner.
              </p>

              <h3 className="font-bold">
                How does it work?
              </h3>
              <p className="text-slate-600">
                You create a room and wait for someone to join. Once someone joins, you will be paired with them and you will be able to start practicing.
              </p>

              <h3 className="font-bold">
                What languages are supported?
              </h3>
              <p className="text-slate-600">
                Currently, only Python is supported. More languages will be added in the future.
              </p>

              <h3 className="font-bold">
                What is the difference between practice and interview?
              </h3>

              <p className="text-slate-600">
                Practice is a room where you can practice your skills with a random partner. Interview is a room where you can interview with a random partner.
              </p>
            </div>

          </div>
          <div className="p-2 flex-1 border-l border-l-slate-200" data-id="mid-content-container">
            middle
          </div>
          <div className="flex flex-col space-y-4 p-2 flex-1 border-l border-l-slate-200 max-w-md" data-id="right-main-sidebar">
            <div className="p-2 flex flex-col space-y-2 bg-sky-200 w-full h-40 rounded-md" data-id="right-practice-card">
              <h2 className="font-bold mb-2">
                Practice
              </h2>

              <p className="text-slate-600">
                Practice your skills with a random partner.
              </p>

              <Button className="bg-blue-600" variant="contained">
                Create Room
              </Button>

            </div>
            <div className="p-2" data-id="right-active-rooms-card">
              <h2 className="font-bold text-slate-600 mb-2">
                Active Rooms
              </h2>

              <div className="p-2 border border-slate-300 rounded-md">
                <div className="flex flex-row justify-between mb-2">
                <h3 className="font-medium">Array of Hope</h3>
                <p className="text-slate-600">2/4 Players</p>
                </div>
                <Chip className="opacity-75 truncate font-bold bg-emerald-200 text-cyan-700 self-center hover:cursor-pointer hover:opacity-100 lowercase row-start-2" label="easy"/>

              </div>


            </div>
            <div className="p-2" data-id="right-recently-active-card">
              <h2 className="font-bold text-slate-600 mb-2">
                Recently Active
              </h2>


            </div>
          </div>
        </div>
      </div>
    
    </div>
  )
}
